#!/usr/bin/env python3
"""Generate validated LaTeX OCR result tables from canonical CSV files."""
from __future__ import annotations

import csv
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent
PAPER_DIR = ROOT.parent / "comparative_analysis"
OVERALL = ROOT / "overall_metrics.csv"
BY_FONT = ROOT / "printed_by_font_metrics.csv"
AUDIT = ROOT / "table_generation_audit.csv"

OVERALL_FIELDS = [
    "access_group", "model", "split", "note", "status", "coverage", "rows",
    "empty_predictions", "exact_match_rate", "hallucination_rate", "cer", "wer",
    "micro_cer", "micro_wer", "char_fscore", "total_cost_usd", "avg_latency_sec",
]
FONT_FIELDS = [
    "access_group", "model", "font", "rows", "empty_predictions",
    "exact_match_rate", "hallucination_rate", "cer", "wer", "micro_cer",
    "micro_wer", "char_fscore", "total_cost_usd", "avg_latency_sec",
]

GROUPS = [
    ("closed", "Closed-Access Models"),
    ("open/general", "Open-Access / General Models"),
    ("arabic-specialized", "Arabic-Specialized Models"),
]
CITES = {
    "GPT-5.4 Mini": "openai2026gpt54mini",
    "Gemini 2.5 Flash": "gemini25flash2025",
    "Gemini 2.5 Pro": "comanici2025gemini25",
    "EasyOCR": "easyocr2020",
    "Gemma-3-27B": "gemma32025",
    "Qwen3-VL-8B": "bai2025qwen3vl",
    "Qwen3-VL-32B": "bai2025qwen3vl",
    "Qwen 8B": "bai2025qwen3vl",
    "Qwen 32B": "bai2025qwen3vl",
    "Qwen2.5-VL-72B": "wang2024qwen2vl",
    "AIN 7B": "heakl2025ain",
    "Qari-OCR": "wasfy2025qariocr",
    "Qari-OCR v0.3": "wasfy2025qariocr",
}
DISPLAY_ORDER = {
    "GPT-5.4 Mini": 1, "Gemini 2.5 Flash": 2, "Gemini 2.5 Pro": 3,
    "EasyOCR": 1, "Gemma-3-27B": 2, "Qwen3-VL-8B": 3, "Qwen 8B": 3,
    "Qwen3-VL-32B": 4, "Qwen 32B": 4, "Qwen2.5-VL-72B": 5,
    "AIN 7B": 1, "Qari-OCR": 2, "Qari-OCR v0.3": 2,
}
FONT_ORDER = ["Akbaar", "Naksh", "Andalus", "Thuluth", "Traditional Arabic", "SimplifiedArabic", "Tahoma", "TimesNewRoman"]
FONT_DISPLAY = {"SimplifiedArabic": "Simplified Arabic", "TimesNewRoman": "Times New Roman"}


def read_csv(path: Path, fields: list[str]) -> list[dict[str, str]]:
    with path.open(encoding="utf-8-sig", newline="") as handle:
        rows = list(csv.DictReader(handle))
    if not rows or set(fields) != set(rows[0]):
        raise ValueError(f"{path.name} does not match its declared canonical schema")
    for index, row in enumerate(rows, start=2):
        missing = [field for field in fields if row.get(field, "") == ""]
        if missing:
            raise ValueError(f"{path.name}:{index} has empty required fields: {missing}")
    return rows


def num(row: dict[str, str], key: str) -> str:
    return f"{float(row[key]):.3f}"


def model_name(row: dict[str, str]) -> str:
    model = row["model"]
    display = {"Qwen 8B": "Qwen3-VL-8B", "Qwen 32B": "Qwen3-VL-32B", "Qari-OCR v0.3": "Qari-OCR", "Gemini 2.5 Pro": "Gemini 2.5 Pro", "Gemini 2.5 Flash": "Gemini 2.5 Flash", "GPT-5.4 Mini": "GPT-5.4 Mini"}.get(model, model)
    return f"{display}~\\cite{{{CITES[model]}}}"


def split_name(row: dict[str, str]) -> str:
    name = "Handwrt" if row["split"] == "handwritten" else "Printed"
    try:
        is_partial = float(row["coverage"]) < 1
    except ValueError:
        is_partial = False
    return name + (r"$^{\dagger}$" if is_partial else "")


def canonical_group(row: dict[str, str]) -> str:
    return "open/general" if row["access_group"] == "open_access" else row["access_group"]

def make_overall(rows: list[dict[str, str]]) -> str:
    kept = [row for row in rows if not (row["model"] == "Qwen2.5-VL-72B" and row["split"] == "printed")]
    lines = [
        "% Auto-generated by generate_paper_tables.py; do not edit numeric cells manually.",
        "\\begin{table*}[!t]", "\\centering", "\\scriptsize", "\\setlength{\\tabcolsep}{1.5pt}",
        "\\renewcommand{\\arraystretch}{1.06}",
        "\\caption{Canonical overall OCR evaluation generated directly from the final row-level metrics. N is the number of evaluated lines; lower CER/WER values are better.}",
        "\\label{tab:overall_metrics}",
        "\\begin{adjustbox}{max width=\\textwidth}",
        "\\begin{tabular}{llr*{8}{r}}", "\\toprule",
        "\\textbf{Model} & \\textbf{Split} & \\textbf{N} & \\textbf{EM} & \\textbf{CER} & \\textbf{WER} & \\textbf{Micro CER} & \\textbf{Micro WER} & \\textbf{Char F1} & \\textbf{Cost (\\$)} & \\textbf{Latency (s)}\\\\",
        "\\midrule",
    ]
    for group, label in GROUPS:
        group_rows = sorted((r for r in kept if canonical_group(r) == group), key=lambda r: (DISPLAY_ORDER[r["model"]], r["split"] != "handwritten"))
        if not group_rows:
            continue
        lines.append(f"\\multicolumn{{11}}{{l}}{{\\textbf{{{label}}}}}\\\\")
        for row in group_rows:
            fields = [model_name(row), split_name(row), f"{int(float(row['rows'])):,}"] + [
                num(row, key) for key in ["exact_match_rate", "cer", "wer", "micro_cer", "micro_wer", "char_fscore", "total_cost_usd", "avg_latency_sec"]
            ]
            if len(fields) != 11:
                raise AssertionError("Overall table row has incorrect field count")
            lines.append(" & ".join(fields) + "\\\\")
        lines.append("\\midrule")
    lines[-1] = "\\bottomrule"
    lines += ["\\end{tabular}", "\\end{adjustbox}",
              "\\parbox{\\textwidth}{\\footnotesize\\textit{Note:} $^{\\dagger}$ Gemini 2.5 Flash printed is the available 7,819-line filtered subset, not a complete 11,392-line result. Qwen2.5-VL-72B printed is a 200-line pilot and is excluded from this complete-comparison table.}",
              "\\end{table*}"]
    return "\n".join(lines) + "\n"


def make_font(rows: list[dict[str, str]], group: str, label: str, out_name: str) -> None:
    models = sorted({r["model"] for r in rows if canonical_group(r) == group}, key=lambda m: DISPLAY_ORDER[m])
    if group == "closed":
        models = [m for m in models if m != "Gemini 2.5 Flash"]
    selected = [r for r in rows if r["model"] in models and canonical_group(r) == group]
    by_model = defaultdict(dict)
    for row in selected:
        by_model[row["model"]][row["font"]] = row
    lines = ["% Auto-generated by generate_paper_tables.py; do not edit numeric cells manually.",
             "\\begin{table*}[!t]", "\\centering", "\\scriptsize", "\\setlength{\\tabcolsep}{1.6pt}",
             "\\renewcommand{\\arraystretch}{1.02}",
             f"\\caption{{Canonical font-wise evaluation of {label.lower()} on printed Arabic. Values are generated directly from the final per-font metrics.}}",
             f"\\label{{tab:{out_name}}}", "\\begin{adjustbox}{max width=\\textwidth}", "\\begin{tabular}{llr*{8}{r}}", "\\toprule",
             "\\textbf{Model} & \\textbf{Font} & \\textbf{N} & \\textbf{EM} & \\textbf{CER} & \\textbf{WER} & \\textbf{Micro CER} & \\textbf{Micro WER} & \\textbf{Char F1} & \\textbf{Cost (\\$)} & \\textbf{Latency (s)}\\\\", "\\midrule"]
    for model in models:
        for font in FONT_ORDER:
            row = by_model[model].get(font)
            if row is None:
                raise ValueError(f"Missing canonical {model} / {font} row")
            fields = [model_name(row), FONT_DISPLAY.get(font, font), f"{int(float(row['rows'])):,}"] + [num(row, key) for key in ["exact_match_rate", "cer", "wer", "micro_cer", "micro_wer", "char_fscore", "total_cost_usd", "avg_latency_sec"]]
            if len(fields) != 11:
                raise AssertionError("Font table row has incorrect field count")
            lines.append(" & ".join(fields) + "\\\\")
        lines.append("\\midrule")
    lines[-1] = "\\bottomrule"
    lines += ["\\end{tabular}", "\\end{adjustbox}", "\\end{table*}"]
    (PAPER_DIR / f"generated_{out_name}_table.tex").write_text("\n".join(lines) + "\n")


def main() -> None:
    overall = read_csv(OVERALL, OVERALL_FIELDS)
    by_font = read_csv(BY_FONT, FONT_FIELDS)
    (PAPER_DIR / "generated_overall_metrics_table.tex").write_text(make_overall(overall))
    make_font(by_font, "closed", "closed-access vision-language models", "printed_closed")
    make_font(by_font, "open/general", "open-access and general OCR/VLM systems", "printed_open")
    make_font(by_font, "arabic-specialized", "Arabic-specialized OCR/VLM systems", "printed_arabic")
    with AUDIT.open("w", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(["source", "table", "rows_validated", "fields_per_data_row", "status"])
        writer.writerow([OVERALL.name, "overall_metrics", len(overall), 11, "pass"])
        for group, label in GROUPS:
            writer.writerow([BY_FONT.name, f"printed_{group}", sum(canonical_group(r) == group for r in by_font), 11, "pass"])

if __name__ == "__main__":
    main()
